# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:06:14+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header

from models import (
    ConsentFetchRequest,
    ConsentRequest,
    ConsentRequestStatusRequest,
    ErrorResponse,
    HealthInformationNotification,
    HeartbeatResponse,
    HIPConsentNotificationResponse,
    HIPHealthInformationRequestAcknowledgement,
    HIRequest,
    HIUConsentNotificationResponse,
    HIUSubscriptionNotificationAcknowledgment,
    HIUSubscriptionRequestNotificationAcknowledgement,
    PatientAuthConfirmRequest,
    PatientAuthInitRequest,
    PatientAuthModeQueryRequest,
    PatientAuthNotificationAcknowledgement,
    PatientCareContextLinkRequest,
    PatientDiscoveryResult,
    PatientIdentificationRequest,
    PatientLinkReferenceResult,
    PatientLinkResult,
    ShareProfileResult,
    SubscriptionRequest,
)

app = MCPProxy(
    contact={'name': 'National Health Authority', 'url': 'https://ndhm.gov.in/'},
    description='Entity which provides health information aggregation services to customers of health care services.\nIt enables customers to fetch their health information from one or more Health Information Providers\n(e.g., Hospitals, Diagnostic Labs, Medical Device Companies), based on their explicit Consent and to share such\naggregated information with Health Information Users i.e. entities in need of such data (e.g., Insurers,\nDoctors, Medical Researchers).\n\n# Specifications\n1. This document maintains only the Health Information Gateway relevant APIs. \n',
    title='Health Data Consent Manager',
    version='0.5',
    servers=[{'description': 'Sandbox', 'url': 'https://dev.ndhm.gov.in/cm'}],
)


@app.post(
    '/v0.5/care-contexts/on-discover',
    description=""" Result of patient care-context discovery request at HIP end. If a matching patient found with zero or more care contexts associated, it is specified as result attribute. If the prior discovery request, resulted in errors then it is specified in the error attribute. Reasons of errors can be 
  1. **more than one definitive match for the given request** 
  2. **no verified identifer was specified**
 """,
    tags=['patient_account_discovery', 'health_data_management'],
)
def post_v0_5_care_contexts_on_discover(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientDiscoveryResult = ...,
):
    """
    Response to patient's account discovery request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consent-requests/init',
    description=""" Creates a consent request to get data about a patient by HIU user. CM should call Gateway - ***/v0.5/consent-requests/on-init*** API with the consent-request-id """,
    tags=['consent_request_management', 'health_data_management'],
)
def post_v0_5_consent_requests_init(
    authorization: str = Header(..., alias='Authorization'), body: ConsentRequest = ...
):
    """
    Create consent request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consent-requests/status',
    description=""" Get status of consent request done previously. CM responds by calling Gateway API - ***/v0.5/consent-requests/on-status*** """,
    tags=['consent_request_management', 'health_data_management'],
)
def post_v0_5_consent_requests_status(
    authorization: str = Header(..., alias='Authorization'),
    body: ConsentRequestStatusRequest = ...,
):
    """
    Get consent request status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/fetch',
    description=""" This API is called when a HIU makes a request to get a consent artefact. For response please refer to the Gateway ***/v0.5/consents/on-fetch*** """,
    tags=['consent_request_management', 'health_data_management'],
)
def post_v0_5_consents_fetch(
    authorization: str = Header(..., alias='Authorization'),
    body: ConsentFetchRequest = ...,
):
    """
    Get consent artefact
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hip/on-notify',
    description=""" This API is called by HIP as acknowledgement to notification of consents, in cases of consent revocation and expiration, notified by CM earlier via Gateway API - ***/v0.5/consents/hip/notify***. 
 """,
    tags=['consent_request_management', 'health_data_management'],
)
def post_v0_5_consents_hip_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    body: HIPConsentNotificationResponse = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hiu/on-notify',
    description=""" This API is called by HIU as acknowledgement to consent notifications, specifically for cases when consent is REVOKED or EXPIRED, notified by CM earlier via Gateway API - ***/v0.5/consents/hiu/notify***.
 """,
    tags=['consent_request_management', 'health_data_management'],
)
def post_v0_5_consents_hiu_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    body: HIUConsentNotificationResponse = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/notify',
    description=""" API called by HIU and HIP during data-transfer. 
1. HIP on transfer of data would send **sessionStatus** - one of [TRANSFERRED, FAILED]
2. HIP would also send **hiStatus** for each *careContextReference* - on of [DELIVERED, ERRORED]
3. HIU on receipt of data would send **sessionStatus** - one of [TRANSFERRED, FAILED]. For example, FAILED when if data was not sent or if invalid data was sent
4. HIU would also send **hiStatus** for each *careContextReference* - one of [OK, ERRORED] 
 """,
    tags=['health_data_management', 'patient_notification_subscriptions'],
)
def post_v0_5_health_information_notify(
    authorization: str = Header(..., alias='Authorization'),
    body: HealthInformationNotification = ...,
):
    """
    Notifications corresponding to events during data flow
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/on-request',
    description=""" This API is called by HIP to acknowledge Health information request receipt. When HIU requests health information, CM generates a transactionId and makes a health information request to the HIP(s). HIPs acknowledgement to the health-information request is coveyed by this API. Either the **hiRequest** or **error** must be specified. **hiRequest** element returns the same transactionId as before with a status indicating that the request is acknowledged.  
 """,
    tags=['health_data_management'],
)
def post_v0_5_health_information_on_request(
    authorization: str = Header(..., alias='Authorization'),
    body: HIPHealthInformationRequestAcknowledgement = ...,
):
    """
    Health information data request acknowledgement from HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/request',
    description=""" HIU request for Health information against a consent id. CM would generate a transactionId against each consent and pass it as trnasaction context / correlation id to the HIP and also return the same to HIU via Gateway API - ***/v0.5/health-information/cm/on-request***. 
 """,
    tags=['health_data_management', 'patient_account_discovery'],
)
def post_v0_5_health_information_request(
    authorization: str = Header(..., alias='Authorization'), body: HIRequest = ...
):
    """
    Health information data request from HIU
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v0.5/heartbeat', tags=['consent_request_management', 'health_data_management']
)
def get_v0_5_heartbeat():
    """
    Get consent request status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/add-contexts',
    description=""" API to submit care-context to CM for HIP initiated linking. The API must accompany the "accessToken" fetched in the users/auth process.  
  1. subsequent usage for accessToken may be invalid if it was meant for one-time usage or if it expired
 """,
    tags=['care_context_links', 'health_data_management'],
)
def post_v0_5_links_link_add_contexts(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientCareContextLinkRequest = ...,
):
    """
    API for HIP initiated care-context linking for patient
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-confirm',
    description=""" Returns a list of linked care contexts with patient reference number.
  1. **Validated and linked account reference number**
  2. **Validated that the token sent from Consent Manager is same as the one generated by HIP**
  3. **Verified that same Consent Manager which made the link request is sending the token**
  4. **Results of unmasked linked care contexts with patient reference number**
 """,
    tags=['care_context_links', 'health_data_management'],
)
def post_v0_5_links_link_on_confirm(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientLinkResult = ...,
):
    """
    Token authenticated by HIP, indicating completion of linkage of care-contexts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-init',
    description=""" Result of patient care-context link request from HIP end. This happens in context of previous discovery of patient found at HIP end, therefore the link requests ought to be in reference to the patient reference and care-context references previously returned by the HIP. The correlation of discovery and link request is maintained through the transactionId. HIP should have
  1. **Validated transactionId in the request to check whether there was a discovery done previously, and the link request corresponds to returned patient care care context references**
  2. **Before returning the response, HIP should have sent an authentication request to the patient(eg: OTP verification)**
  3. **HIP should communicate the mode of authentication of a successful request**
  4. **HIP subsequently should expect the token passed via /link/confirm against the link.referenceNumber passed in this call**




















  
The error section in the body, represents the potential errors that may have occurred. Possible reasons:
  1. **Patient reference number is invalid**
  2. **Care context reference numbers are invalid**
 """,
    tags=['care_context_links'],
)
def post_v0_5_links_link_on_init(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientLinkReferenceResult = ...,
):
    """
    Response to patient's care context link request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/find',
    description=""" This API is meant for identify to patient given her consent-manager-user-id. CM subsequently makes the /on-find Gateway API call with results. 
 """,
    tags=['patient_account_discovery', 'consent_request_management'],
)
def post_v0_5_patients_find(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientIdentificationRequest = ...,
):
    """
    Identify a patient by her consent-manager user-id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/profile/on-share',
    description=""" Result of patient share profile request at HIP end.
 """,
    tags=['patient_account_discovery', 'health_data_management'],
)
def post_v0_5_patients_profile_on_share(
    authorization: str = Header(..., alias='Authorization'),
    body: ShareProfileResult = ...,
):
    """
    Response to patient's share profile request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscription-requests/cm/init',
    description=""" creates a request for subscription. The subscription categories can be for care-contexts linkages or availability of data against existing care-contexts. Note that the requester must have HIU role """,
    tags=['patient_notification_subscriptions'],
)
def post_v0_5_subscription_requests_cm_init(
    authorization: str = Header(..., alias='Authorization'),
    body: SubscriptionRequest = ...,
):
    """
    Request for subscription
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscription-requests/hiu/on-notify',
    description=""" This API is called by HIU as acknowledgement to subscription request relevant notifications. 
 """,
    tags=['patient_notification_subscriptions', 'user_access_authentication'],
)
def post_v0_5_subscription_requests_hiu_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    body: HIUSubscriptionRequestNotificationAcknowledgement = ...,
):
    """
    Callback API for /subscription-requests/hiu/notify to acknowledge receipt of notification.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscriptions/hiu/on-notify',
    description=""" This API is called by HIU as acknowledgement to consent notifications, specifically for cases when consent is REVOKED or EXPIRED.
 """,
    tags=['patient_notification_subscriptions', 'user_access_authentication'],
)
def post_v0_5_subscriptions_hiu_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    body: HIUSubscriptionNotificationAcknowledgment = ...,
):
    """
    Callback API for /subscriptions/hiu/notify to acknowledge receipt of notification.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/confirm',
    description=""" This API is called by HIP/HIUs to confirm authentication of users. The transactionId returned by the previous callback API /users/auth/on-init must be sent. If Authentication is successful the callback API will send an "access token" for subsequent purpose specific API calls. Note only **credential.authCode** or **credential.demographic** should be sent
  1. demographic details are only required for  demographic auth as of now. 
  2. demographic details are required only in MEDIATED cases and if the **auth.mode** so demands. e.g. if **auth.mode** is DEMOGRAPHICS. Usually for demographic authentication, the name, gender and DOB must be exactly as specified in User Account.
  3. demographic.identifier is optional, however maybe required if authentication so mandates. 
  4. credential.authCode is required for other MEDIATED authentication like MOBILE_OTP, AADHAAR_OTP. 
 """,
    tags=['user_access_authentication', 'consent_request_management'],
)
def post_v0_5_users_auth_confirm(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientAuthConfirmRequest = ...,
):
    """
    Confirmation request sending token, otp or other authentication details from HIP/HIU for confirmation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/fetch-modes',
    description=""" This API is meant for identify supported authentication modes for a patient given a specific purpose
 """,
    tags=['user_access_authentication', 'patient_account_discovery'],
)
def post_v0_5_users_auth_fetch_modes(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientAuthModeQueryRequest = ...,
):
    """
    Get a patient's authentication modes relevant to specified purpose
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/init',
    description=""" This API is called by HIPs to initiate authentication of users. A transactionId is retuned by the corresponding callback API for confirmation of user auth.
 """,
    tags=['user_access_authentication'],
)
def post_v0_5_users_auth_init(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientAuthInitRequest = ...,
):
    """
    Initialize authentication from HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-notify',
    description=""" This API is called by HIU/HIPs to confirm acknowledgement for receipt of auth notification is case of DIRECT authentication. 
 """,
    tags=['user_access_authentication', 'health_data_management'],
)
def post_v0_5_users_auth_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientAuthNotificationAcknowledgement = ...,
):
    """
    callback API from HIU/HIPs as acknowledgement of auth notification (in case of DIRECT auth)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
