# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:06:14+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field, RootModel


class AuthConfirmIdentifierType(Enum):
    MOBILE = 'MOBILE'


class AuthenticationMode(Enum):
    MOBILE_OTP = 'MOBILE_OTP'
    DIRECT = 'DIRECT'
    DEMOGRAPHICS = 'DEMOGRAPHICS'
    AADHAAR_OTP = 'AADHAAR_OTP'


class CareContextDefinition(BaseModel):
    careContextReference: str = Field(..., examples=['Episode1'])
    patientReference: str = Field(..., examples=['batman@tmh'])


class CareContextRepresentation(BaseModel):
    display: str
    referenceNumber: str


class Status(Enum):
    OK = 'OK'
    UNKNOWN = 'UNKNOWN'


class ConsentAcknowledgement(BaseModel):
    consentId: str = Field(..., examples=['<consent-artefact-id>'])
    status: Status


class ConsentManagerPatientID(BaseModel):
    id: str = Field(..., examples=['hinapatel79@ndhm'])


class DateRange(BaseModel):
    from_: datetime = Field(..., alias='from')
    to: datetime


class Code(Enum):
    integer_1000 = 1000
    integer_10001 = 10001


class Error(BaseModel):
    code: Code
    message: str


class ErrorResponse(BaseModel):
    error: Optional[Error] = None


class SessionStatus(Enum):
    ACKNOWLEDGED = 'ACKNOWLEDGED'


class HiRequest(BaseModel):
    sessionStatus: SessionStatus
    transactionId: UUID


class HITypeEnum(Enum):
    OPConsultation = 'OPConsultation'
    Prescription = 'Prescription'
    DischargeSummary = 'DischargeSummary'
    DiagnosticReport = 'DiagnosticReport'


class Status1(Enum):
    OK = 'OK'


class Acknowledgement(BaseModel):
    eventId: str = Field(..., examples=['subscription event Id'])
    status: Status1


class Acknowledgement1(BaseModel):
    status: Status1
    subscriptionRequestId: str = Field(..., examples=['subscription Id'])


class Type(Enum):
    HIU = 'HIU'
    HIP = 'HIP'


class Notifier(BaseModel):
    id: str = Field(..., examples=[100005])
    type: Type


class SessionStatus1(Enum):
    TRANSFERRED = 'TRANSFERRED'
    FAILED = 'FAILED'


class HiStatus(Enum):
    DELIVERED = 'DELIVERED'
    OK = 'OK'
    ERRORED = 'ERRORED'


class StatusResponse(BaseModel):
    careContextReference: str
    description: Optional[str] = None
    hiStatus: HiStatus = Field(..., examples=['OK'])


class StatusNotification(BaseModel):
    hipId: str = Field(..., examples=['max'])
    sessionStatus: SessionStatus1
    statusResponses: Optional[List[StatusResponse]] = None


class Status3(Enum):
    UP = 'UP'
    DOWN = 'DOWN'


class IdentifierType(Enum):
    MOBILE = 'MOBILE'
    MR = 'MR'


class KeyObject(BaseModel):
    expiry: datetime
    keyValue: str
    parameters: str = Field(..., examples=['Curve25519/32byte random key'])


class CommunicationMedium(Enum):
    MOBILE = 'MOBILE'
    EMAIL = 'EMAIL'


class Meta(BaseModel):
    communicationExpiry: Optional[str] = Field(None, examples=['2019-12-30T12:01:55Z'])
    communicationHint: Optional[str] = None
    communicationMedium: CommunicationMedium


class OrganizationRepresentation(BaseModel):
    id: str


class Type1(Enum):
    HIP = 'HIP'
    HIU = 'HIU'


class Requester1(BaseModel):
    id: str = Field(..., examples=['100005'])
    type: Type1


class Status4(Enum):
    OK = 'OK'


class Acknowledgement2(BaseModel):
    status: Status4


class PatientAuthPurpose(Enum):
    LINK = 'LINK'
    KYC = 'KYC'
    KYC_AND_LINK = 'KYC_AND_LINK'


class PatientAuthRequester(BaseModel):
    id: str = Field(..., examples=[100005])
    type: Type1


class Patient(BaseModel):
    careContexts: List[CareContextRepresentation]
    display: str
    referenceNumber: str = Field(
        ..., description='patient reference id at HIP', examples=['TMH-PUID-001']
    )


class PatientCareContextLink(BaseModel):
    accessToken: str = Field(
        ...,
        description='AccessToken fetched in the user auth process for the purpose specified',
    )
    patient: Patient


class PatientGender(Enum):
    M = 'M'
    F = 'F'
    O = 'O'
    U = 'U'


class Patient1(BaseModel):
    id: str = Field(..., examples=['hinapatel79@ndhm'])


class Type3(Enum):
    HIU = 'HIU'
    HIP = 'HIP'


class Requester2(BaseModel):
    id: str = Field(..., examples=[100005])
    type: Type3


class Query2(BaseModel):
    patient: Patient1
    requester: Requester2


class AuthenticationType(Enum):
    DIRECT = 'DIRECT'
    MEDIATED = 'MEDIATED'


class Link(BaseModel):
    authenticationType: AuthenticationType
    meta: Optional[Meta] = None
    referenceNumber: str


class Patient2(BaseModel):
    careContexts: List[CareContextRepresentation]
    display: str
    referenceNumber: str


class PatientRepresentation(BaseModel):
    careContexts: List[CareContextRepresentation]
    display: str
    matchedBy: Optional[List[IdentifierType]] = None
    referenceNumber: str


class AccessMode(Enum):
    VIEW = 'VIEW'
    STORE = 'STORE'
    QUERY = 'QUERY'
    STREAM = 'STREAM'


class Unit(Enum):
    HOUR = 'HOUR'
    WEEK = 'WEEK'
    DAY = 'DAY'
    MONTH = 'MONTH'
    YEAR = 'YEAR'


class Frequency(BaseModel):
    repeats: Optional[int] = None
    unit: Optional[Unit] = None
    value: Optional[int] = None


class Permission(BaseModel):
    accessMode: AccessMode
    dataEraseAt: datetime
    dateRange: DateRange
    frequency: Frequency


class RequestReference(BaseModel):
    requestId: UUID = Field(..., description='the requestId that was passed')


class Identifier1(BaseModel):
    system: Optional[str] = Field(None, examples=['https://www.mciindia.org'])
    type: str = Field(..., examples=['REGNO'])
    value: str = Field(..., examples=['MH1001'])


class Requester(BaseModel):
    identifier: Optional[Identifier1] = None
    name: str = Field(..., examples=['Dr. Manju'])


class Status5(Enum):
    SUCCESS = 'SUCCESS'
    FAILURE = 'FAILURE'


class ShareProfileAcknowledgement(BaseModel):
    healthId: str = Field(..., examples=['<username>@<suffix>'])
    status: Status5


class SubscriptionCategory(Enum):
    LINK = 'LINK'


class SubscriptionPeriod(BaseModel):
    from_: datetime = Field(..., alias='from')
    to: datetime


class TimestampSchema(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Date time format in UTC, includes miliseconds YYYY-MM-DDThh:mm:ss.vZ',
    )


class UsePurpose(BaseModel):
    code: str = Field(..., description='From the fixed set, documented at refUri')
    refUri: Optional[AnyUrl] = None
    text: str


class UuidSchema(RootModel[UUID]):
    root: UUID = Field(..., examples=['a1s2c932-2f70-3ds3-a3b5-2sfd46b12a18d'])


class Consent(BaseModel):
    id: str


class KeyMaterial(BaseModel):
    cryptoAlg: str = Field(..., examples=['ECDH'])
    curve: str = Field(..., examples=['Curve25519'])
    dhPublicKey: KeyObject
    nonce: str = Field(..., examples=['3fa85f64-5717-4562-b3fc-2c963f66afa6'])


class AuthConfirmIdentifier(BaseModel):
    type: AuthConfirmIdentifierType
    value: str = Field(..., examples=['+919800083232'])


class ConsentFetchRequest(BaseModel):
    consentId: str
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    timestamp: TimestampSchema


class ConsentModel(BaseModel):
    careContexts: Optional[List[CareContextDefinition]] = None
    hiTypes: List[HITypeEnum]
    hip: Optional[OrganizationRepresentation] = None
    hiu: OrganizationRepresentation
    patient: ConsentManagerPatientID
    permission: Permission
    purpose: UsePurpose
    requester: Requester


class ConsentRequest(BaseModel):
    consent: ConsentModel
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request.',
        examples=['499a5a4a-7dda-4f20-9b67-e24589627061'],
    )
    timestamp: TimestampSchema


class ConsentRequestStatusRequest(BaseModel):
    consentRequestId: str
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    timestamp: TimestampSchema


class HIPConsentNotificationResponse(BaseModel):
    acknowledgement: Optional[ConsentAcknowledgement] = None
    error: Optional[Error] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class HIPHealthInformationRequestAcknowledgement(BaseModel):
    error: Optional[Error] = None
    hiRequest: Optional[HiRequest] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class HiRequest1(BaseModel):
    consent: Consent
    dataPushUrl: str
    dateRange: DateRange
    keyMaterial: KeyMaterial


class HIRequest(BaseModel):
    hiRequest: HiRequest1
    requestId: UuidSchema
    timestamp: TimestampSchema


class HIUConsentNotificationResponse(BaseModel):
    acknowledgement: Optional[List[ConsentAcknowledgement]] = None
    error: Optional[Error] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class HIUSubscriptionNotificationAcknowledgment(BaseModel):
    acknowledgement: Optional[Acknowledgement] = None
    error: Optional[Error] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class HIUSubscriptionRequestNotificationAcknowledgement(BaseModel):
    acknowledgement: Optional[Acknowledgement1] = None
    error: Optional[Error] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class Notification(BaseModel):
    consentId: UuidSchema
    doneAt: datetime
    notifier: Notifier
    statusNotification: StatusNotification
    transactionId: UuidSchema


class HealthInformationNotification(BaseModel):
    notification: Notification
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request.',
        examples=['499a5a4a-7dda-4f20-9b67-e24589627061'],
    )
    timestamp: TimestampSchema


class HeartbeatResponse(BaseModel):
    error: Optional[Error] = None
    status: Optional[Status3] = None
    timestamp: Optional[TimestampSchema] = None


class Identifier(BaseModel):
    type: IdentifierType
    value: str = Field(..., examples=['+919800083232'])


class Query(BaseModel):
    authMode: Optional[AuthenticationMode] = None
    id: str = Field(
        ...,
        description='id  of the patient understood by the CM',
        examples=['hinapatel@ndhm'],
    )
    purpose: PatientAuthPurpose
    requester: PatientAuthRequester


class PatientAuthInitRequest(BaseModel):
    query: Query
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    timestamp: TimestampSchema


class Query1(BaseModel):
    id: str = Field(..., examples=['hinapatel79@ndhm'])
    purpose: PatientAuthPurpose
    requester: Requester1


class PatientAuthModeQueryRequest(BaseModel):
    query: Query1
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    timestamp: TimestampSchema


class PatientAuthNotificationAcknowledgement(BaseModel):
    acknowledgement: Optional[Acknowledgement2] = None
    error: Optional[Error] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class PatientCareContextLinkRequest(BaseModel):
    link: PatientCareContextLink
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    timestamp: TimestampSchema


class PatientDemographic(BaseModel):
    dateOfBirth: str = Field(
        ..., description='date of birth in YYYY-MM-DD format.', examples=['1972-02-29']
    )
    gender: PatientGender
    identifier: Optional[AuthConfirmIdentifier] = None
    name: str = Field(..., examples=['janki das'])


class PatientDiscoveryResult(BaseModel):
    error: Optional[Error] = None
    patient: Optional[PatientRepresentation] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema
    transactionId: UUID


class PatientIdentificationRequest(BaseModel):
    query: Query2
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    timestamp: TimestampSchema


class PatientLinkReferenceResult(BaseModel):
    error: Optional[Error] = None
    link: Optional[Link] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema
    transactionId: UuidSchema


class PatientLinkResult(BaseModel):
    error: Optional[Error] = None
    patient: Optional[Patient2] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class ShareProfileResult(BaseModel):
    acknowledgement: ShareProfileAcknowledgement
    error: Optional[Error] = None
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    resp: RequestReference
    timestamp: TimestampSchema


class Subscription(BaseModel):
    categories: List[SubscriptionCategory]
    hips: Optional[List[OrganizationRepresentation]] = None
    hiu: OrganizationRepresentation
    patient: ConsentManagerPatientID
    period: SubscriptionPeriod
    purpose: UsePurpose


class SubscriptionRequest(BaseModel):
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request.',
        examples=['499a5a4a-7dda-4f20-9b67-e24589627061'],
    )
    subscription: Subscription
    timestamp: TimestampSchema


class Credential(BaseModel):
    authCode: Optional[str] = None
    demographic: Optional[PatientDemographic] = None


class PatientAuthConfirmRequest(BaseModel):
    credential: Credential = Field(
        ...,
        description='note, demographic details are only required for demographic verfication.',
    )
    requestId: UUID = Field(
        ...,
        description='a nonce, unique for each HTTP request',
        examples=['5f7a535d-a3fd-416b-b069-c97d021fbacd'],
    )
    timestamp: TimestampSchema
    transactionId: str
